import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const OBSIDIAN_PLUGIN_PATH = path.resolve(".obsidian/plugins/smartwrite-publisher");

const copyToObsidian = () => {
	if (!fs.existsSync(OBSIDIAN_PLUGIN_PATH)) {
		fs.mkdirSync(OBSIDIAN_PLUGIN_PATH, { recursive: true });
	}
	fs.copyFileSync("main.js", path.join(OBSIDIAN_PLUGIN_PATH, "main.js"));
	fs.copyFileSync("manifest.json", path.join(OBSIDIAN_PLUGIN_PATH, "manifest.json"));
	fs.copyFileSync("styles.css", path.join(OBSIDIAN_PLUGIN_PATH, "styles.css"));
	console.log("Plugin deployed to Obsidian.");
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	copyToObsidian();
	process.exit(0);
} else {
	await context.watch();
}
