import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const OBSIDIAN_PLUGIN_PATH = "/Users/zander/Library/CloudStorage/GoogleDrive-zander.cattapreta@zedicoes.com/My Drive/_ programação/_ smartwrite_publisher/.obsidian/plugins/smartwrite-publisher";

const copyToObsidian = () => {
	// Create dist directory if it doesn't exist
	const distPath = "dist";
	if (!fs.existsSync(distPath)) {
		fs.mkdirSync(distPath);
	}

	// Copy manifest.json and styles.css to dist for consistency with release assets
	fs.copyFileSync("manifest.json", path.join(distPath, "manifest.json"));
	fs.copyFileSync("styles.css", path.join(distPath, "styles.css"));

	if (!fs.existsSync(OBSIDIAN_PLUGIN_PATH)) {
		fs.mkdirSync(OBSIDIAN_PLUGIN_PATH, { recursive: true });
	}
	// Copy from dist to Obsidian plugin path
	fs.copyFileSync(path.join(distPath, "main.js"), path.join(OBSIDIAN_PLUGIN_PATH, "main.js"));
	fs.copyFileSync(path.join(distPath, "manifest.json"), path.join(OBSIDIAN_PLUGIN_PATH, "manifest.json"));
	fs.copyFileSync(path.join(distPath, "styles.css"), path.join(OBSIDIAN_PLUGIN_PATH, "styles.css"));
	console.log("Plugin deployed to Obsidian.");
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js", // Change output file to dist/main.js
	minify: prod,
});

if (prod) {
	await context.rebuild();
	copyToObsidian();
	process.exit(0);
} else {
	await context.watch();
}
